-- =====================================================================
-- Frases engraçadas/sarcásticas espalhadas pelo site (sorteadas a cada visita).
-- Editáveis no painel /admin/frases.php.
--
--   lugar: faixa (faixa do topo, troca sozinha) · mapa · estado (piada do estado, no mapa) ·
--          mural · compra (janela de compra) · rodape · entrada (página de escolha do pote)
--   lado:  em qual pote aparece — direita | esquerda | ambos
--   uf:    só para lugar = estado
-- =====================================================================

CREATE TABLE frases (
    id             INT UNSIGNED NOT NULL AUTO_INCREMENT,
    lugar          VARCHAR(20)  NOT NULL,
    lado           ENUM('direita','esquerda','ambos') NOT NULL DEFAULT 'ambos',
    uf             CHAR(2)      NULL,
    texto          VARCHAR(300) NOT NULL,
    ativo          TINYINT(1)   NOT NULL DEFAULT 1,
    criado_em      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em  DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_frases_lugar (ativo, lugar, lado)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO frases (lugar, lado, uf, texto) VALUES
    ('faixa', 'direita', NULL, 'Azeitona não muda de pote a cada eleição. Pimenta muda de opinião a cada assembleia.'),
    ('faixa', 'direita', NULL, 'Aqui o único vermelho permitido é o recheio da azeitona.'),
    ('faixa', 'direita', NULL, 'Dica de conservado: salmoura dura mais que promessa de campanha.'),
    ('faixa', 'direita', NULL, 'Pimenta arde na hora. Azeitona conserva por gerações.'),
    ('faixa', 'direita', NULL, 'Na dúvida, conserve. Na certeza, conserve também.'),
    ('faixa', 'direita', NULL, 'A pimentada marcou uma assembleia para decidir se ia marcar uma assembleia.'),
    ('faixa', 'direita', NULL, 'Tradição é quando seu avô já tinha uma azeitona no pote.'),
    ('faixa', 'direita', NULL, 'Azeitona com caroço tem princípios. E às vezes quebra um dente.'),
    ('faixa', 'direita', NULL, 'O outro pote pediu mais Estado. A gente pediu mais azeitona.'),
    ('faixa', 'direita', NULL, 'Se a pimenta fosse boa mesmo, não precisava de tanto cartaz.'),
    ('faixa', 'direita', NULL, 'Conservador que é conservador guarda até o vidro do pote.'),
    ('faixa', 'direita', NULL, 'Verde, preta ou recheada: diversidade que funciona sem cota.'),
    ('faixa', 'direita', NULL, 'Pimenteiro reclama do nosso pote, mas passa o dia espiando aqui.'),
    ('faixa', 'direita', NULL, 'A esquerda quer dividir tudo. Menos a pimenta dela.'),
    ('faixa', 'direita', NULL, 'Churrasco sem azeitona é assembleia sem pauta: só barulho.'),
    ('faixa', 'esquerda', NULL, 'Azeitona é só uma pimenta que desistiu da luta.'),
    ('faixa', 'esquerda', NULL, 'Conservador conserva tudo: até a mesma opinião desde 1950.'),
    ('faixa', 'esquerda', NULL, 'Na salmoura desde sempre, mudando nunca.'),
    ('faixa', 'esquerda', NULL, 'A pimenta arde. A azeitona só fica ali, boiando.'),
    ('faixa', 'esquerda', NULL, 'O pote de lá está esperando o momento certo para mudar. Desde 1822.'),
    ('faixa', 'esquerda', NULL, 'Aqui a ardência é coletiva. Lá cada azeitona tem o próprio caroço.'),
    ('faixa', 'esquerda', NULL, 'Azeitona recheada: a única coisa com diversidade no pote de lá.'),
    ('faixa', 'esquerda', NULL, 'Eles conservam. A gente tempera.'),
    ('faixa', 'esquerda', NULL, 'Tem azeitoneiro que só sai do pote para reclamar do preço da gasolina.'),
    ('faixa', 'esquerda', NULL, 'Pimenta não tem patrão: tem assembleia.'),
    ('faixa', 'esquerda', NULL, 'O pote vizinho tem tampa. O nosso tem pauta.'),
    ('faixa', 'esquerda', NULL, 'Azeitona é ótima na empada. Na política fica sem gosto.'),
    ('faixa', 'esquerda', NULL, 'Nossa pimenta é orgânica, sindicalizada e sem agrotóxico.'),
    ('faixa', 'esquerda', NULL, 'Tem mais pimenta aqui do que bandeira em carreata do lado de lá.'),
    ('faixa', 'esquerda', NULL, 'Azeitoneiro acha que ardência é coisa de comunista. É só tempero, tio.'),
    ('faixa', 'ambos', NULL, 'Dois potes, um país, zero acordo.'),
    ('faixa', 'ambos', NULL, 'Pimenta ou azeitona: no fim, tudo vai parar na mesma pizza.'),
    ('faixa', 'ambos', NULL, 'Aviso: nenhum parente foi bloqueado durante a produção deste site. Ainda.'),
    ('faixa', 'ambos', NULL, 'O grupo da família mandou avisar: política no almoço de domingo continua proibida.'),
    ('faixa', 'ambos', NULL, 'Aqui ninguém fica em cima do muro. O muro foi vendido para comprar mais pimenta.'),
    ('faixa', 'ambos', NULL, 'Quem fica no meio-termo vira palmito.'),
    ('faixa', 'ambos', NULL, 'Discutir política faz bem: queima calorias e amizades.'),
    ('faixa', 'ambos', NULL, 'Não é briga, é debate com tempero.'),
    ('faixa', 'ambos', NULL, 'Seu tio já escolheu o pote dele. E você?'),
    ('faixa', 'ambos', NULL, 'Direita e esquerda concordam em uma coisa: o outro lado está errado.'),
    ('faixa', 'ambos', NULL, 'O Centrão entrou no site, viu os preços e saiu negociando desconto.'),
    ('faixa', 'ambos', NULL, 'Estudos mostram: 100% dos debates de internet terminam com "pesquisa aí".'),
    ('faixa', 'ambos', NULL, 'Nenhuma azeitona ou pimenta foi ferida na criação deste site.'),
    ('faixa', 'ambos', NULL, 'Em cima do muro só tem a tampa do pote.'),
    ('faixa', 'ambos', NULL, 'Se o debate esquentar, a azeitona conserva e a pimenta agradece.'),
    ('mural', 'direita', NULL, 'Mural conservador: opinião com prazo de validade vencido não entra.'),
    ('mural', 'direita', NULL, 'Publicar aqui é como pôr azeitona na empada: dá sabor, sem exagero.'),
    ('mural', 'direita', NULL, 'Pimenteiro comentando? Normal. Eles adoram um pote alheio.'),
    ('mural', 'direita', NULL, 'Aqui a gente conversa. Quem grita é a pimentada.'),
    ('mural', 'direita', NULL, 'Regra do mural: pode discordar, só não pode tirar a tampa.'),
    ('mural', 'esquerda', NULL, 'Mural da resistência: se ninguém reclamar, a gente se preocupa.'),
    ('mural', 'esquerda', NULL, 'Aqui se debate. Lá se conserva.'),
    ('mural', 'esquerda', NULL, 'Azeitoneiro comentando? Deixa, faz bem para o sódio deles.'),
    ('mural', 'esquerda', NULL, 'Publicou e ninguém curtiu? Chama uma assembleia e vota de novo.'),
    ('mural', 'esquerda', NULL, 'Regra do mural: ardência sim, grosseria não.'),
    ('mural', 'ambos', NULL, 'Comentar do outro lado pode. Bloquear o tio, não.'),
    ('mural', 'ambos', NULL, 'Dica: vídeo de 40 minutos ninguém assiste. De nenhum dos lados.'),
    ('mural', 'ambos', NULL, 'Antes de postar, respire. Depois poste do mesmo jeito.'),
    ('mapa', 'direita', NULL, 'Cada estado vermelho é um churrasco de família a menos.'),
    ('mapa', 'direita', NULL, 'Mapa verde é mapa conservado: nada estraga.'),
    ('mapa', 'direita', NULL, 'Conquistou um estado? Conserve. É a nossa especialidade.'),
    ('mapa', 'direita', NULL, 'Estado cinza é estado sem opinião. Tipo o primo que só manda meme.'),
    ('mapa', 'direita', NULL, 'A pimentada pinta o mapa rápido. Mas desbota na primeira chuva.'),
    ('mapa', 'esquerda', NULL, 'Cada estado verde é um tio a mais mandando áudio de 7 minutos.'),
    ('mapa', 'esquerda', NULL, 'Mapa vermelho não é ameaça, é previsão do tempo: vai esquentar.'),
    ('mapa', 'esquerda', NULL, 'A azeitona avança devagar: conservador não gosta de mudança, nem de fronteira.'),
    ('mapa', 'esquerda', NULL, 'Estado cinza é território livre. Ocupa!'),
    ('mapa', 'esquerda', NULL, 'Estado conquistado é estado com mais tempero.'),
    ('mapa', 'ambos', NULL, 'O mapa muda a cada compra. Igual opinião de político.'),
    ('mapa', 'ambos', NULL, 'Nenhum estado foi anexado à força. Só com pimenta e azeitona.'),
    ('mapa', 'ambos', NULL, 'Geografia nunca foi tão emocionante. Seu professor ficaria orgulhoso.'),
    ('compra', 'direita', NULL, 'Investimento seguro: azeitona não sofre com inflação ideológica.'),
    ('compra', 'direita', NULL, 'Uma azeitona por ano sai mais barato que um sermão do seu tio.'),
    ('compra', 'direita', NULL, 'Garanta a sua antes que a pimentada invente um imposto sobre azeitona.'),
    ('compra', 'direita', NULL, 'Leve uma para você e outra para o cunhado que ainda está em cima do muro.'),
    ('compra', 'esquerda', NULL, 'Pimenta no pote é luta com recibo.'),
    ('compra', 'esquerda', NULL, 'Uma pimenta custa menos que um cartaz de passeata.'),
    ('compra', 'esquerda', NULL, 'Garanta a sua antes que privatizem o pote.'),
    ('compra', 'esquerda', NULL, 'Leve uma para você e outra para o tio que jura que azeitona é neutra.'),
    ('compra', 'ambos', NULL, 'Nenhum dos dois lados aceita fiado.'),
    ('compra', 'ambos', NULL, 'Entrega imediata: o pote já está aqui, esperando você.'),
    ('compra', 'ambos', NULL, 'Pagamento em Pix: a única coisa que os dois lados usam sem reclamar.'),
    ('rodape', 'direita', NULL, 'Feito com salmoura e zero dinheiro público.'),
    ('rodape', 'direita', NULL, 'Este site não usa cookies de pimenta.'),
    ('rodape', 'esquerda', NULL, 'Feito com ardência e trabalho coletivo (hora extra não paga, mas com consciência de classe).'),
    ('rodape', 'esquerda', NULL, 'Este site é 100% livre de latifúndio de azeitona.'),
    ('rodape', 'ambos', NULL, 'Nenhum debate foi resolvido nesta página.'),
    ('rodape', 'ambos', NULL, 'Se você e seu tio concordaram em algo aqui, avise: é histórico.'),
    ('rodape', 'ambos', NULL, 'Proibido ficar em cima do muro: o muro não aguenta o peso.'),
    ('entrada', 'ambos', NULL, 'Escolha com calma: trocar de pote depois pega mal no grupo da família.'),
    ('entrada', 'ambos', NULL, 'Pimenta ou azeitona? A pergunta mais difícil desde "bolacha ou biscoito".'),
    ('entrada', 'ambos', NULL, 'Não existe pote do meio. O Centrão tentou, mas pediu um cargo.'),
    ('entrada', 'ambos', NULL, 'Nenhuma opinião será respeitada, mas todas serão comentadas.'),
    ('entrada', 'ambos', NULL, 'Qualquer semelhança com o almoço de domingo não é mera coincidência.'),
    ('entrada', 'ambos', NULL, 'Os dois potes juram que o outro está vazio.'),
    ('entrada', 'ambos', NULL, 'Aqui você pode discordar à vontade. Só não pode ficar sem pote.'),
    ('entrada', 'ambos', NULL, 'Pimenta arde, azeitona conserva, palmito fica em cima do muro.'),
    ('estado', 'ambos', 'AC', 'Sim, existe. E está esperando a sua pimenta ou azeitona para provar.'),
    ('estado', 'ambos', 'AC', 'Aqui o debate chega com fuso horário: ainda é ontem.'),
    ('estado', 'ambos', 'AL', 'A praia é tão bonita que ninguém quer discutir política, só tomar água de coco.'),
    ('estado', 'ambos', 'AL', 'Até a treta é morna por aqui: 30 graus à sombra.'),
    ('estado', 'ambos', 'AP', 'Metade no hemisfério norte, metade no sul. Nem direita nem esquerda: bem no meio do mundo.'),
    ('estado', 'ambos', 'AP', 'Em cima da linha do Equador: o único lugar onde ficar no meio é geografia, não covardia.'),
    ('estado', 'ambos', 'AM', 'Tão grande que cabem os dois potes e ainda sobra floresta.'),
    ('estado', 'ambos', 'AM', 'O encontro das águas é o único encontro sem briga por aqui.'),
    ('estado', 'ambos', 'BA', 'Aqui ninguém tem pressa, nem para escolher o pote.'),
    ('estado', 'ambos', 'BA', 'O debate só começa depois do acarajé. Com ou sem pimenta, meu rei?'),
    ('estado', 'ambos', 'CE', 'Terra do humor: o pote que perder vira piada de stand-up.'),
    ('estado', 'ambos', 'CE', 'Aqui até a derrota vem com trocadilho.'),
    ('estado', 'ambos', 'DF', 'Onde os dois lados discutem de terno e ninguém escuta.'),
    ('estado', 'ambos', 'DF', 'Tem mais opinião por metro quadrado do que ipê.'),
    ('estado', 'ambos', 'ES', 'Capixaba não briga, só come moqueca (e não é baiana, viu?).'),
    ('estado', 'ambos', 'ES', 'Vizinho de todo mundo, lembrado por poucos, disputado pelos dois potes.'),
    ('estado', 'ambos', 'GO', 'Aqui a disputa se resolve no sertanejo, em dupla.'),
    ('estado', 'ambos', 'GO', 'O pequi divide mais opiniões que a política.'),
    ('estado', 'ambos', 'MA', 'Tem lençóis de areia, mas ninguém dorme no ponto.'),
    ('estado', 'ambos', 'MA', 'O reggae acalma até o debate mais ardido.'),
    ('estado', 'ambos', 'MT', 'Espaço de sobra para plantar soja e opinião.'),
    ('estado', 'ambos', 'MT', 'O calor já vem apimentado de fábrica.'),
    ('estado', 'ambos', 'MS', 'O irmão que ninguém confunde. (Mentira, todo mundo confunde.)'),
    ('estado', 'ambos', 'MS', 'No Pantanal o jacaré assiste ao debate de camarote.'),
    ('estado', 'ambos', 'MG', 'O mineiro ainda está pensando em qual pote entrar. Come quieto, uai.'),
    ('estado', 'ambos', 'MG', 'A decisão sai junto com o pão de queijo: devagar e no ponto.'),
    ('estado', 'ambos', 'PA', 'Com açaí de verdade, o debate fica roxo.'),
    ('estado', 'ambos', 'PA', 'Chove toda tarde: até a discussão tem hora marcada.'),
    ('estado', 'ambos', 'PB', 'O sol nasce aqui primeiro. A treta também.'),
    ('estado', 'ambos', 'PB', 'O forró resolve o que o debate não resolve.'),
    ('estado', 'ambos', 'PR', 'Aqui a polêmica é bolacha ou biscoito, não esquerda ou direita.'),
    ('estado', 'ambos', 'PR', 'O pinhão é neutro. O resto, nem tanto.'),
    ('estado', 'ambos', 'PE', 'Frevo de dia, debate de noite e ninguém cansa.'),
    ('estado', 'ambos', 'PE', 'Até a sombrinha de frevo escolhe um lado.'),
    ('estado', 'ambos', 'PI', '40 graus: a pimenta se sente em casa, a azeitona pede ventilador.'),
    ('estado', 'ambos', 'PI', 'O calor esquenta qualquer discussão, nem precisa de pimenta.'),
    ('estado', 'ambos', 'RJ', 'Aqui o debate é na praia, entre um mate e um biscoito de polvilho.'),
    ('estado', 'ambos', 'RJ', 'Todo mundo tem opinião e ninguém chega no horário.'),
    ('estado', 'ambos', 'RN', 'Com tanto vento, até a opinião muda de lado.'),
    ('estado', 'ambos', 'RN', 'O pote vencedor ganha passeio de buggy nas dunas. (Não ganha, mas seria legal.)'),
    ('estado', 'ambos', 'RS', 'Tchê, aqui a treta é no churrasco, com o chimarrão passando de mão em mão.'),
    ('estado', 'ambos', 'RS', 'O debate dura o tempo de um chimarrão. Ou seja, não acaba nunca.'),
    ('estado', 'ambos', 'RO', 'Estado jovem, cheio de energia e de lugar vago no mapa.'),
    ('estado', 'ambos', 'RO', 'Ainda está escolhendo o pote. Corre que dá tempo.'),
    ('estado', 'ambos', 'RR', 'Tão ao norte que o debate chega de cachecol.'),
    ('estado', 'ambos', 'RR', 'O primeiro pote que chegar leva o monte mais famoso daqui de brinde (de mentirinha).'),
    ('estado', 'ambos', 'SC', 'Praia, serra e Oktoberfest. Tem azeitona até no chope.'),
    ('estado', 'ambos', 'SC', 'Até a neve de São Joaquim tem opinião formada.'),
    ('estado', 'ambos', 'SP', 'A treta está parada no trânsito há três horas.'),
    ('estado', 'ambos', 'SP', 'O debate é rápido: todo mundo tem reunião às 15h.'),
    ('estado', 'ambos', 'SE', 'Pequeno no mapa, gigante na treta.'),
    ('estado', 'ambos', 'SE', 'Aqui cabe tudo, menos gente em cima do muro.'),
    ('estado', 'ambos', 'TO', 'O caçula do Brasil ainda está decidindo o que quer ser quando crescer.'),
    ('estado', 'ambos', 'TO', 'No Jalapão tem areia de sobra para enterrar a derrota de qualquer pote.');
