-- =====================================================================
-- Convite pra treta no WhatsApp (botão embaixo do pote, partials/hero.php). Editáveis em /cozinha/frases.
--
--   convite_botao  texto do botão (curto, cabe no celular), sorteado a cada visita · lado ambos
--   convite_whats  mensagem que abre no WhatsApp, sorteada · lado = pote de quem convida.
--                  O link do pote vai no fim, numa linha só dele (é o que puxa o banner og-<lado>.png na prévia).
-- =====================================================================

INSERT INTO frases (lugar, lado, uf, texto) VALUES
    ('convite_botao', 'ambos', NULL, 'Chamar alguém pra treta'),
    ('convite_botao', 'ambos', NULL, 'Convocar reforço'),
    ('convite_botao', 'ambos', NULL, 'Chama o tio do zap'),
    ('convite_botao', 'ambos', NULL, 'Puxa um pro pote'),
    ('convite_botao', 'ambos', NULL, 'Convoca a tropa'),
    ('convite_botao', 'ambos', NULL, 'Bota lenha na treta'),
    ('convite_botao', 'ambos', NULL, 'Arrasta um parente'),
    ('convite_botao', 'ambos', NULL, 'Chama pra briga'),
    ('convite_botao', 'ambos', NULL, 'Recruta um aliado'),
    ('convite_botao', 'ambos', NULL, 'Provoca um amigo'),
    ('convite_botao', 'ambos', NULL, 'Chama o cunhado'),
    ('convite_botao', 'ambos', NULL, 'Convida pra treta'),
    ('convite_botao', 'ambos', NULL, 'Chama a tia do grupo'),
    ('convite_botao', 'ambos', NULL, 'Engrossa o pote'),
    ('convite_botao', 'ambos', NULL, 'Pede reforço'),
    ('convite_botao', 'ambos', NULL, 'Traz mais um'),
    ('convite_botao', 'ambos', NULL, 'Incendeia o grupo'),
    ('convite_botao', 'ambos', NULL, 'Chama o time'),
    ('convite_botao', 'ambos', NULL, 'Cutuca um amigo'),
    ('convite_botao', 'ambos', NULL, 'Espalha a treta'),

    -- quem convida é azeitona (Direita Conservada)
    ('convite_whats', 'direita', NULL, '🫒 Convocação oficial: a pimentada tá enchendo o pote deles e eu não vou assistir calado. Preciso de você aqui:'),
    ('convite_whats', 'direita', NULL, '🫒 Te convido pra treta mais saudável do Brasil: azeitona contra pimenta. O tio do zap já chegou, só falta você:'),
    ('convite_whats', 'direita', NULL, '🫒 Bora pra treta? O grupo da família vai virar terra arrasada de novo, mas agora com placar:'),
    ('convite_whats', 'direita', NULL, '🫒 A Pimenta da Resistência tá ardendo de inveja do nosso pote. Vem conservar comigo:'),
    ('convite_whats', 'direita', NULL, '🫒 A pimentada marcou assembleia pra decidir se entra no pote. A gente só entra. Vem:'),
    ('convite_whats', 'direita', NULL, '🫒 Se a esquerda ganhar esse placar, vou ouvir no almoço de domingo até 2030. Me ajuda:'),
    ('convite_whats', 'direita', NULL, '🫒 Azeitona sozinha é petisco. Azeitona em grupo é pote. Entra no meu:'),
    ('convite_whats', 'direita', NULL, '🫒 Tô recrutando gente de caroço duro pra enfrentar a pimentada. Você tem o perfil:'),
    ('convite_whats', 'direita', NULL, '🫒 A pimenta arde na hora. A azeitona conserva por gerações. Vem provar que eu tô certo:'),
    ('convite_whats', 'direita', NULL, '🫒 Seu cunhado entrou no pote da pimenta. Vai deixar barato?'),
    ('convite_whats', 'direita', NULL, '🫒 Aviso de família: quem não entrar no pote vai sentar do lado do cunhado pimenteiro no Natal:'),
    ('convite_whats', 'direita', NULL, '🫒 Tá tendo treta boa e você aí de fora comendo pipoca. Pega uma azeitona e vem:'),
    ('convite_whats', 'direita', NULL, '🫒 A pimentada fez vaquinha, fez cartaz e fez textão. A gente só enche o pote. Vem:'),
    ('convite_whats', 'direita', NULL, '🫒 Conservador que é conservador não deixa o pote vazio. Cumpra seu dever:'),
    ('convite_whats', 'direita', NULL, '🫒 Me disseram que você tem opinião forte. Prova aqui, na frente da pimentada:'),
    ('convite_whats', 'direita', NULL, '🫒 O outro pote pediu mais Estado. Eu peço mais você no nosso. Vem:'),
    ('convite_whats', 'direita', NULL, '🫒 Tô perdendo a discussão no grupo da família. Preciso de reforço urgente:'),
    ('convite_whats', 'direita', NULL, '🫒 Treta liberada, pimenta provocando e placar apertado. Só falta você:'),
    ('convite_whats', 'direita', NULL, '🫒 A esquerda quer dividir tudo, menos o pote de pimenta. Vem mostrar como se enche um pote de verdade:'),
    ('convite_whats', 'direita', NULL, '🫒 Pimenteiro reclama do nosso pote, mas passa o dia espiando. Vem dar motivo:'),
    ('convite_whats', 'direita', NULL, '🫒 Entrar no pote sai mais barato que terapia depois do grupo da família. Confia:'),
    ('convite_whats', 'direita', NULL, '🫒 Chamando todos os tios do zap, primos do churrasco e vizinhos de opinião forte. Você foi convocado:'),
    ('convite_whats', 'direita', NULL, '🫒 Azeitona com caroço tem princípios. E às vezes quebra dente de pimenteiro. Vem:'),
    ('convite_whats', 'direita', NULL, '🫒 A pimentada tá dizendo que a gente não enche o pote. Bora calar a boca deles:'),
    ('convite_whats', 'direita', NULL, '🫒 Tô montando a bancada da salmoura. Tem vaga pra você:'),
    ('convite_whats', 'direita', NULL, '🫒 Não é briga, é debate. Mas se for briga, tô do lado da azeitona. E você?'),
    ('convite_whats', 'direita', NULL, '🫒 Ou você entra no pote ou vira petisco de pimenteiro. Escolha com sabedoria:'),
    ('convite_whats', 'direita', NULL, '🫒 Última chamada antes da pimentada virar o placar. Vem conservar:'),
    ('convite_whats', 'direita', NULL, '🫒 A treta tá boa, o placar tá quente e o pote tá te esperando. Sem desculpa:'),
    ('convite_whats', 'direita', NULL, '🫒 Tradição é quando seu avô já tinha azeitona no pote. Começa a sua:'),

    -- quem convida é pimenta (Pimenta da Resistência)
    ('convite_whats', 'esquerda', NULL, '🌶️ Convocação urgente: a azeitonada tá enchendo o pote deles e eu não vou ficar de braço cruzado. Vem:'),
    ('convite_whats', 'esquerda', NULL, '🌶️ Te convido pra treta mais ardida do Brasil: pimenta contra azeitona. O tio do zap já tá infartando, só falta você:'),
    ('convite_whats', 'esquerda', NULL, '🌶️ Bora pra treta? O grupo da família vai pegar fogo de novo, agora com placar:'),
    ('convite_whats', 'esquerda', NULL, '🌶️ A Direita Conservada tá azeda com o nosso pote. Vem resistir comigo:'),
    ('convite_whats', 'esquerda', NULL, '🌶️ Azeitona é só uma pimenta que desistiu da luta. Não desiste, vem:'),
    ('convite_whats', 'esquerda', NULL, '🌶️ Se a direita ganhar esse placar, o tio vai mandar áudio de 8 minutos comemorando. Me ajuda a evitar:'),
    ('convite_whats', 'esquerda', NULL, '🌶️ Pimenta sozinha arde. Pimenta em grupo é resistência. Entra no meu pote:'),
    ('convite_whats', 'esquerda', NULL, '🌶️ Tô recrutando gente que não tem medo de arder. Você tem o perfil:'),
    ('convite_whats', 'esquerda', NULL, '🌶️ Azeitona passa a vida boiando na salmoura. Pimenta faz barulho. Vem fazer barulho:'),
    ('convite_whats', 'esquerda', NULL, '🌶️ Seu cunhado entrou no pote da azeitona. Vai deixar barato?'),
    ('convite_whats', 'esquerda', NULL, '🌶️ Aviso de família: quem não entrar no pote vai aguentar o tio do zap sozinho no Natal:'),
    ('convite_whats', 'esquerda', NULL, '🌶️ Tá tendo treta boa e você aí de fora comendo pipoca. Pega uma pimenta e vem:'),
    ('convite_whats', 'esquerda', NULL, '🌶️ A azeitonada tá conservando até opinião do século passado. Vem temperar esse debate:'),
    ('convite_whats', 'esquerda', NULL, '🌶️ Resistência que é resistência não deixa o pote vazio. Chegou sua hora:'),
    ('convite_whats', 'esquerda', NULL, '🌶️ Me disseram que você tem opinião forte. Prova aqui, na frente da azeitonada:'),
    ('convite_whats', 'esquerda', NULL, '🌶️ O outro pote tá cheio de caroço. O nosso tem tempero. Vem:'),
    ('convite_whats', 'esquerda', NULL, '🌶️ Tô perdendo a discussão no grupo da família. Preciso de reforço urgente:'),
    ('convite_whats', 'esquerda', NULL, '🌶️ Treta liberada, azeitona provocando e placar apertado. Só falta você:'),
    ('convite_whats', 'esquerda', NULL, '🌶️ A azeitona diz que conserva a tradição. A gente conserva a chama acesa. Vem:'),
    ('convite_whats', 'esquerda', NULL, '🌶️ Azeitoneiro reclama do nosso pote, mas passa o dia espiando. Vem dar motivo:'),
    ('convite_whats', 'esquerda', NULL, '🌶️ Entrar no pote sai mais barato que terapia depois do grupo da família. Confia:'),
    ('convite_whats', 'esquerda', NULL, '🌶️ Chamando a militância do churrasco, as tias engajadas e os primos do DCE. Você foi convocado:'),
    ('convite_whats', 'esquerda', NULL, '🌶️ Pimenta pequena arde mais. Vem provar que tamanho não é documento:'),
    ('convite_whats', 'esquerda', NULL, '🌶️ A azeitonada tá dizendo que a gente não enche o pote. Bora fazer eles engolirem o caroço:'),
    ('convite_whats', 'esquerda', NULL, '🌶️ Tô montando a bancada da ardência. Tem vaga pra você:'),
    ('convite_whats', 'esquerda', NULL, '🌶️ Não é briga, é debate. Mas se for briga, tô do lado da pimenta. E você?'),
    ('convite_whats', 'esquerda', NULL, '🌶️ Ou você entra no pote ou vira aperitivo de azeitoneiro. Escolha com sabedoria:'),
    ('convite_whats', 'esquerda', NULL, '🌶️ Última chamada antes da azeitonada virar o placar. Vem arder:'),
    ('convite_whats', 'esquerda', NULL, '🌶️ A treta tá boa, o placar tá quente e o pote tá te esperando. Sem desculpa:'),
    ('convite_whats', 'esquerda', NULL, '🌶️ Assembleia aprovada por unanimidade: você precisa entrar no pote. Vem:');
